# HTTP
server {
    listen 80;
    server_name no-mess.ru www.no-mess.ru;

    # Перенаправление всех HTTP-запросов на HTTPS
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl;
    server_name no-mess.ru www.no-mess.ru;

    ssl_certificate /etc/ssl/no-mess.crt;
    ssl_certificate_key /etc/ssl/no-mess.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}